version: "3"

services:
  npm:
    image: node:16.0.0
    user: node
    working_dir: /home/node/sources
    tty: true
    stdin_open: true
    entrypoint: npm
    volumes:
      - .:/home/node/sources
