name: Package

on:
  push:
    branches:
      - production

jobs:
  package:
    name: Publish the package to the NPM registry
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Environment
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Dependencies installation
        run: docker-compose run --rm --user root -T npm install

      - name: Build
        run: docker-compose run --rm --user root -T npm run build

      - name: Publish
        run: 'docker-compose run --rm --user root -T npm publish --access public || true'
